### ISSUE TITLE
PlacePicker not working On MIUI v.7.02 Unable to start activity ComponentInfo{com.google.android.gms/com.google.android.location.places.ui.placepicker.v1.PlacePickerActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Configuration android.content.res.Resources.getConfiguration()' 

### ISSUE THREAD

**Issue by igorexax3mal** [googlesamples/android-play-places#44]
5-18 22:49:08.944 1610-1610/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: com.google.android.gms.ui, PID: 1610
                                                 java.lang.RuntimeException: Unable to start activity ComponentInfo{com.google.android.gms/com.google.android.location.places.ui.placepicker.v1.PlacePickerActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Configuration android.content.res.Resources.getConfiguration()' on a null object reference
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2330)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2392)
                                                     at android.app.ActivityThread.access$800(ActivityThread.java:154)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1308)
                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                     at android.os.Looper.loop(Looper.java:135)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5273)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at java.lang.reflect.Method.invoke(Method.java:372)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)
                                                  Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Configuration android.content.res.Resources.getConfiguration()' on a null object reference
                                                     at android.view.SurfaceView.init(SurfaceView.java:231)
                                                     at android.view.SurfaceView.<init>(SurfaceView.java:193)
                                                     at maps.X.x.<init>(Unknown Source)
                                                     at maps.X.v.<init>(Unknown Source)
                                                     at maps.E.u.<init>(Unknown Source)
                                                     at maps.E.u.a(Unknown Source)
                                                     at maps.ag.ad.a(Unknown Source)
                                                     at maps.ag.t.a(Unknown Source)
                                                     at maps.ag.Q.a(Unknown Source)
                                                     at vn.onTransact(:com.google.android.gms.DynamiteModulesB:66)
                                                     at android.os.Binder.transact(Binder.java:380)
                                                     at rdt.a(SourceFile:205)
                                                     at rbh.a(SourceFile:96)
                                                     at mvn.b(SourceFile:209)
                                                     at mvm.a(SourceFile:99)
                                                     at rbj.a(SourceFile:1257)
                                                     at mvl.a(SourceFile:161)
                                                     at com.google.android.gms.maps.MapView.a(SourceFile:5201)
                                                     at afjm.onActivityCreated(SourceFile:253)
                                                     at com.google.android.chimera.FragmentProxy.onActivityCreated(SourceFile:407)
                                                     at android.support.v4.app.Fragment.performActivityCreated(SourceFile:1970)
                                                     at ex.a(SourceFile:1092)
                                                     at ex.a(SourceFile:1248)
                                                     at dy.run(SourceFile:738)
                                                     at ex.i(SourceFile:1613)
                                                     at es.c(SourceFile:330)
                                                     at en.onStart(SourceFile:547)
                                                     at com.google.android.chimera.container.ActivityProxy.superOnStart(SourceFile:2398)
                                                     at com.google.android.chimera.Activity.onStart(SourceFile:402)
                                                     at com.google.android.places.ui.placepicker.v1.PlacePickerChimeraActivity.onStart(SourceFile:240)
                                                     at com.google.android.chimera.Activity.publicOnStart(SourceFile:407)
                                                     at com.google.android.chimera.container.ActivityProxy.onStart(SourceFile:286)
                                                     at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1239)
                                                     at android.app.Activity.performStart(Activity.java:6057)
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2293)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2392) 
                                                     at android.app.ActivityThread.access$800(ActivityThread.java:154) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1308) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                     at android.os.Looper.loop(Looper.java:135) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:5273) 
                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                     at java.lang.reflect.Method.invoke(Method.java:372) 
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)

**Comment by stanislavin** [comment]
Same issue MIUI 7.3.2.0

Referencing issue from google code
https://code.google.com/p/gmaps-api-issues/issues/detail?id=9071

**Comment by luckcoolla** [comment]
Is any workaround here?

**Comment by iiitmahesh** [comment]
same problem for me also.@stanislavin Did find any solution or workaround??

**Comment by stanislavin** [comment]
@iiitmahesh @luckcoolla I haven't found any workaround for it. I experienced this on my personal phone and my personal solution was to switch to CM->LineageOS. Maybe they fixed it in recent versions of MIUI.

**Comment by CTNCardoso** [comment]
App:
https://play.google.com/store/apps/details?id=br.com.ctncardoso.ctncar
Play-services version: 11.0.1

The same problem is occurring on the following devices.

API: 23
Version: 6.0.1
Version Number: MMB29M
Language: pt
Locale: português (Brasil)
Fabricante: LENOVO
Model: Lenovo A6020l36

API: 23
Version: 6.0
Version Number: MRA58K
Language: en
Locale: English (United Kingdom)
Fabricante: LGE
Model: LG-H815

API: 23
Version: 6.0
Version Number: MRA58K
Language: pt
Locale: português (Brasil)
Fabricante: LGE
Model: LG-K430

API: 23
Version: 6.0.1
Version Number: MMB29M
Language: en
Locale: English (United Kingdom)
Fabricante: bq
Model: Aquaris X5

API: 22
Version: 5.1.1
Version Number: LMY47V
Language: pt
Locale: português (Brasil)
Fabricante: LGE
Model: LG-K130

API: 23
Version: 6.0.1
Version Number: 26.3.B.1.33
Language: pt
Locale: português (Brasil)
Fabricante: Sony
Model: E2363

API: 23
Version: 6.0
Version Number: MRA58K
Language: es
Locale: español (Estados Unidos)
Fabricante: LGE
Model: LG-D851

**Comment by CTNCardoso** [comment]
App:
https://play.google.com/store/apps/details?id=br.com.ctncardoso.ctncar
Play-services version: 11.0.1

The same problem is occurring on the following devices.


APARELHO
Aparelho Redmi 4 Pro (markw) 
Fabricante Xiaomi 
Tipo de dispositivo Smartphone 
Idioma do dispositivo Português 
Marca da CPU Qualcomm 
Modelo de CPU MSM8953 
Plataforma nativa armeabi-v7a, armeabi, arm64-v8a 
RAM (MB) 3072 
Tamanho da tela 1080 × 1920 
Densidade da tela (dpi) 480 
Versão OpenGL ES 3.1 
SO Android 6.0

Aparelho Redmi 4 Pro (markw) 
Fabricante Xiaomi 
Tipo de dispositivo Smartphone 
Idioma do dispositivo Russo 
Marca da CPU Qualcomm 
Modelo de CPU MSM8953 
Plataforma nativa armeabi-v7a, armeabi, arm64-v8a 
RAM (MB) 3072 
Tamanho da tela 1080 × 1920 
Densidade da tela (dpi) 480 
Versão OpenGL ES 3.1 
SO Android 6.0

Aparelho LG K10 LTE (m253) 
Fabricante LGE 
Tipo de dispositivo Smartphone 
Idioma do dispositivo Português 
Marca da CPU Mediatek 
Modelo de CPU MT6753 
Plataforma nativa armeabi-v7a, armeabi 
RAM (MB) 1536 
Tamanho da tela 720 × 1280 
Densidade da tela (dpi) 320 
Versão OpenGL ES 3.0 	
SO Android 6.0

Aparelho HTC Desire 10 pro (htc_a56dj_pro_dugl) 
Fabricante HTC 
Tipo de dispositivo Smartphone 
Idioma do dispositivo Inglês 
Marca da CPU Mediatek 
Modelo de CPU MT6577 
Plataforma nativa armeabi-v7a, armeabi, arm64-v8a 
RAM (MB) 2048 
Tamanho da tela 1080 × 1920 
Densidade da tela (dpi) 480 
Versão OpenGL ES 3.0 
SO Android 6.0

Aparelho LG X power (mk6p) 
Fabricante LGE 
Tipo de dispositivo Smartphone 
Idioma do dispositivo Português 
Marca da CPU Mediatek 
Modelo de CPU MT6735 
Plataforma nativa armeabi-v7a, armeabi 
RAM (MB) 2048 
Tamanho da tela 720 × 1280 
Densidade da tela (dpi) 320 
Versão OpenGL ES 3.0 
SO Android 6.0

Aparelho Mi 5 (gemini) 
Fabricante Xiaomi 
Tipo de dispositivo Smartphone 
Idioma do dispositivo Russo 
Marca da CPU Qualcomm 
Modelo de CPU MSM8996 
Plataforma nativa armeabi-v7a, armeabi, arm64-v8a 
RAM (MB) 4096 
Tamanho da tela 1080 × 1920 
Densidade da tela (dpi) 480 
Versão OpenGL ES 3.1 
SO Android 6.0

Aparelho Redmi Note 4 (mido) 
Fabricante Xiaomi 
Tipo de dispositivo Smartphone 
Idioma do dispositivo Inglês 
Marca da CPU Qualcomm 
Modelo de CPU MSM8953 
Plataforma nativa armeabi-v7a, armeabi, arm64-v8a 
RAM (MB) 3072 
Tamanho da tela 1080 × 1920 
Densidade da tela (dpi) 480 
Versão OpenGL ES 3.1 
SO Android 6.0

Aparelho Lenovo K5 (A6020l36) 
Fabricante Lenovo Mobile 
Tipo de dispositivo Smartphone 
Idioma do dispositivo Português 
Marca da CPU Qualcomm 
Modelo de CPU MSM8929 
Plataforma nativa armeabi-v7a, armeabi, arm64-v8a 
RAM (MB) 2048 
Tamanho da tela 1080 × 1920 
Densidade da tela (dpi) 480 
Versão OpenGL ES 3.0 
SO Android 6.0

**Comment by alexmirash** [comment]
java.lang.RuntimeException: Unable to resume activity {com.google.android.gms/com.google.android.location.places.ui.placepicker.PlacePickerActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void com.google.maps.api.android.lib6.impl.bn.o()' on a null object reference

Getting this crash on Redmi 4 Prime, Android 6.0.1, MIUI 8.2

**Comment by iiitmahesh** [comment]
After added this to my android manifest we have solved this problem. (I am not sure about this solution.)

**android:hardwareAccelerated="true"** 


```
<activity 
android:name=".MainActivity" 
android:label="@string/app_name" 
android:screenOrientation="portrait" 
android:hardwareAccelerated="true" 
android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
>
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
```

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
