### ISSUE TITLE
AutoCompleteSearchLocation to show the selected place from the list.

### ISSUE THREAD

**Issue by 19rajasekaran** [googlesamples/android-play-places#59]
Hi,

I am using PlaceAutocompleteAdapter class to auto search a location in android when we entering text by text in edit text box. I faced a crash issue when second text is entered and the crash issue shows in the above line "return DataBufferUtils.freezeAndClose(autocompletePredictions);". Please help me to resolve this issue.

I used this library..
    compile 'com.google.android.gms:play-services:10.2.0'
    compile 'com.google.android.gms:play-services-maps:10.2.0'
    compile 'com.google.android.gms:play-services-location:10.2.0'

I pasted the crash issue that i faced in my side.

 java.lang.NoSuchFieldError: No static field zzcuT of type [Ljava/lang/String; in class Lcom/google/android/gms/internal/zzbxw; or its superclasses (declaration of 'com.google.android.gms.internal.zzbxw' appears in /data/app/com.farmersfridge.app-1/base.apk:classes2.dex)
 at com.google.android.gms.internal.zzblo.zzUS(Unknown Source)
 at com.google.android.gms.internal.zzblo.<init>(Unknown Source)
 at com.google.android.gms.internal.zzblo.zzT(Unknown Source)
 at com.google.android.gms.location.places.internal.zzab.zzb(Unknown Source)
 at com.google.android.gms.location.places.internal.zzc.getPlaceTypes(Unknown Source)
 at com.google.android.gms.location.places.internal.zzc.zzII(Unknown Source)
 at com.google.android.gms.location.places.internal.zzc.freeze(Unknown Source)
 at com.google.android.gms.common.data.DataBufferUtils.freezeAndClose(Unknown Source)
 at com.farmersfridge.app.adapter. PlaceAutocompleteAdapter.getAutocomplete(PlaceAutocompleteAdapter.java:229)
 at com.farmersfridge.app.adapter. PlaceAutocompleteAdapter.access$000(PlaceAutocompleteAdapter.java:54)
 at com.farmersfridge.app.adapter. PlaceAutocompleteAdapter$1.performFiltering(PlaceAutocompleteAdapter.java:149)
 at android.widget.Filter$RequestHandler.handleMessage(Filter.java:234)
 at android.os.Handler.dispatchMessage(Handler.java:102)
 at android.os.Looper.loop(Looper.java:145)
 at android.os.HandlerThread.run(HandlerThread.java:61)

Thanks.

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
